### PR TITLE
Add CI with github actions

### PR DESCRIPTION
**Pull request by zyhou**
- [x] Add jest (wait https://github.com/Euregan/aperoweb/pull/27)
- [x] Add eslint
- [ ] See what other do (now.sh, create release, tag, etc...)

### CODE REVIEW

**Comment by Euregan** [comment]
Can't now handle this?

**Comment by zyhou** [comment]
> Can't now handle this?

You can now. I create an issue about exploring other Github action

**Comment by Euregan** [comment]
> 
> 
> > Can't now handle this?
> 
> You can now. I create an issue about exploring other Github action

I meant now as in _now_ by zeit :D

**Comment by zyhou** [comment]
> > > Can't now handle this?
> > 
> > 
> > You can now. I create an issue about exploring other Github action
> 
> I meant now as in _now_ by zeit :D

Ahhh. I don't know, never see you can pass tests on now.sh

**Comment by Euregan** [comment]
Hmm, yeah, it's probably better to run that on Github anyway

**Review by Euregan — APPROVED** [review]

**Pull request merged**
